apiVersion: v1
kind: Service
metadata:
  name: service-password
  namespace: viptech
spec:
  selector:
    app: password
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort
  externalTrafficPolicy: Local   # <- preserva o IP real do cliente